services:
  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: todo-keycloak

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    command:
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: todo-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - todo-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: todo-grafana
    user: "472"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    networks:
      - todo-network
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  todo-app:
    build: .
    container_name: todo-spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tododb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - todo-network
    restart: unless-stopped

  todo-react:
    image: node:20
    container_name: todo-react-app
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3001:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - todo-network
    stdin_open: true
    tty: true

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: